version: '3'

services:
  web:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/home/node/src
      - /home/node/src/node_modules
    links:
      - db
    environment:
      DB_URL: mongodb://db:27017
      PORT: 8080
      JWT_SECRET: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTYzMzY4MTgwMywiaWF0IjoxNjMzNjgxODAzfQ.k_tVkUgg5TwZeqONnD3E3JOoArvwg7V7kDNymsVg03w
      JWT_EXP: 10d
  db:
    image: mongo:5
