version: '3'

services:
  web:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/home/node/src
      - /home/node/src/node_modules
    links:
      - db
    environment:
      MONGO_CONNECTION_STRING: mongodb://db:27017
  db:
    image: mongo:5
